on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@main

      - name: Run read-yaml dev
        id: var
        uses: ./
        with:
          file: './dev.yml'
          key-path: '["runs", "using"]'

      - name: Get read-yaml output
        run: echo "${{ steps.var.outputs.data }}"
